---

apache_version: 2.4.6
apache_mpm: prefork
apache_listen_ports:
  - 80
apache_include_conf:
  - '/etc/httpd/conf.d/autoindex.conf'
  - '/etc/httpd/conf.d/userdir.conf'
  - '/etc/httpd/conf.d/welcome.conf'
apache_sub_packages:
  - mod_ssl
  - httpd-devel

apache_rewrite_rule:
  - from: https://fromweb.com
    to: https://toweb.com
    status: 301
  - from: https://hogehoge.com
    to: https://okeoke.com/
    status: 200
